<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>18d20e20-0085-44fe-a37d-f9b602a27cc9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="8.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileServiceAPI\FileServiceAPI.csproj" />
    <ProjectReference Include="..\UserServiceAPI\UserServiceAPI.csproj" />
  </ItemGroup>

</Project>
