name: ApiGateway Pipeline

on:
  push:
    paths:
      - 'File-It/ApiGateway/**'
  pull_request:
    paths:
      - 'File-It/ApiGateway/**'
  workflow_dispatch: 

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: [8.0.x]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore File-It/ApiGateway/ApiGateway.csproj


    # BUILDING
    - name: Build
      run: dotnet build --no-restore --configuration Release File-It/ApiGateway/ApiGateway.csproj

    #- name: Test
    # run: dotnet test --no-restore --verbosity normal --configuration Release File-It/ApiGateway/ApiGateway.csproj

    - name: Publish
      run: dotnet publish --no-restore --configuration Release --output ./output File-It/ApiGateway/ApiGateway.csproj

      
    # DOCKER IMAGE  
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/apigateway:latest -f File-It/ApiGateway/Dockerfile .

    # DOCKER HUB
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/apigateway:latest
