name: Security Scan

on:
  push:
    paths:
      - 'File-It/FileServiceAPI/**'
  pull_request:
    paths:
      - 'File-It/FileServiceAPI/**'
  workflow_dispatch: 

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Microservice Locally
        run: |
          dotnet run --project File-It/FileServiceAPI/FileServiceAPI.csproj &

      - name: Wait for Microservice to Start
        run: |
          sleep 30 

      - name: Start OWASP ZAP scan
        run: |
          docker run -t zaproxy/zap-stable zap-baseline.py \
          -t http://localhost:5002 \
          -r zap_report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: zap_report.html
